image: node:20-bullseye

stages:
  - lint
  - build

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/
  policy: pull-push

before_script:
  - npm ci

lint:
  stage: lint
  script:
    - npm run lint

build:
  stage: build
  variables:
    NODE_ENV: production
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 7 days
  needs: ["lint"]
